### ISSUE TITLE
Fetching unknown Font

### ISSUE THREAD

**Issue by DemonMartin** [dimaportenko/react-native-liquid-gauge#1]
Seems like the module tries to fetch a font which isn't correctly defined in module.
 
 
 Error:
 ⨯ ./node_modules/react-native-liquid-gauge/lib/module/LiquidGauge.js:102:23
Module not found: Can't resolve '../assets/fonts/Roboto-Bold.ttf'

**Comment by dimaportenko** [comment]
I believe I tested it. So can you share more details? 
1. What kind of RN project have you tried Expo Go, Expo Bare Flow, React Native CLI? 
2.  How did you install package?

**Comment by DemonMartin** [comment]
1. My project was made using the Next.js Framework.
2. Using NPM :)

**Comment by dimaportenko** [comment]
This library was made for React Native (mainly mobile applications). If you have web project you can use following https://gist.github.com/brattonc/5e5ce9beee483220e2f6

**Comment by shasherazi** [comment]
I have the same error on a react native cli app

**Comment by dimaportenko** [comment]
@shasherazi, please share how to reproduce this error.
